### ISSUE TITLE
Prize booth can delete cards when redeeming >1 ticket

### ISSUE THREAD

**Issue by Hexcede** [otDan/GameEnhancementCards#1]
This was happening before the `2.0.0` update, I am not sure if it's resolved. This was in online mode but I reproduced the issue in sandbox as well.

Redeeming tickets (when you have more than one) with the Prize Booth card was causing my entire card list to be deleted.

Trying to redeem tickets again later with the Prize Booth card seemed to sometimes fix the issue and all of your cards would start to work again.

**Comment by otDan** [comment]
This has been fixed in the last update. 
Feel free to open the issue again if you notice this still persisting.
